---
apiVersion: ui.scality.com/v1alpha1
kind: ScalityUI
metadata:
  name: scality-ui
  namespace: ui
spec:
  image: ghcr.io/scality/metalk8s/shell-ui:v130.0.0-dev-130.0.0-alpha.2-77-gce11d6eff
  mountPath: /usr/share/nginx/html/shell
  productName: RING
