---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ui.scality.com.ui-operator.scality.com
  resources:
  - scalityuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.scality.com.ui-operator.scality.com
  resources:
  - scalityuis/finalizers
  verbs:
  - update
- apiGroups:
  - ui.scality.com.ui-operator.scality.com
  resources:
  - scalityuis/status
  verbs:
  - get
  - patch
  - update
