---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.scality.com
  resources:
  - scalityuicomponentexposers
  - scalityuicomponents
  - scalityuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ui.scality.com
  resources:
  - scalityuicomponentexposers/finalizers
  - scalityuicomponents/finalizers
  - scalityuis/finalizers
  verbs:
  - update
- apiGroups:
  - ui.scality.com
  resources:
  - scalityuicomponentexposers/status
  - scalityuicomponents/status
  - scalityuis/status
  verbs:
  - get
  - patch
  - update
