# permissions for end users to view scalityuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ui-operator
    app.kubernetes.io/managed-by: kustomize
  name: scalityui-viewer-role
rules:
- apiGroups:
  - ui.scality.com.ui-operator.scality.com
  resources:
  - scalityuis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ui.scality.com.ui-operator.scality.com
  resources:
  - scalityuis/status
  verbs:
  - get
