apiVersion: ui.scality.com/v1alpha1
kind: ScalityUIComponentExposer
metadata:
  name: dummy-ui-exposer
  namespace: ui
spec:
  scalityUI: "scality-ui"
  scalityUIComponent: "dummy-ui"
  appHistoryBasePath: "/"
  auth:
    kind: "OIDC"
    providerUrl: "https://auth.example.com"
    redirectUrl: "/dashboard"
    clientId: "my-client-id"
    responseType: "code"
    scopes: "openid email profile groups"
    providerLogout: true
  selfConfiguration:
    url: "https://example.com"
    testArray: ["test1", "test2"]
